---
ID: "cb8f898d-aca5-4f5e-b5ce-08ad096243c8"
Parent: "a20fb511-b5f7-4b40-af2e-b90c9fcfb162"
Template: "854ba861-63ea-4a0c-8c7b-541e9a7ec4c1"
Path: "/sitecore/system/Settings/Rules/placeholder-renderings/Tags/Default"
DB: master
SharedFields:
- ID: "42f77151-098f-496a-94cf-590b7edeeabe"
  Hint: Tags
  Type: Multilist
  Value: "{E429B5CF-BAA4-47E0-A820-F297D4136CFF}"
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: 
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20150119T164127
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\ameagle
